image: python:3.11

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/
    - .venv/

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest

test:
  stage: test
  script:
    - pytest
  artifacts:
    reports:
      junit: report.xml
    when: always
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'